# Generated by Django 4.0.8 on 2023-10-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0002_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Buses')),
                ('route', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('duration', models.DurationField()),
                ('bus_type', models.CharField(max_length=100)),
                ('available_seats', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
