# Generated by Django 4.0.8 on 2023-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('adults', models.PositiveIntegerField()),
                ('childrens', models.PositiveIntegerField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
