# Generated by Django 4.0.8 on 2023-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
