# Generated by Django 4.0.8 on 2023-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_alter_bus_duration_alter_reservation_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
